apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-client-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/444jop/gitops_room9.git
    targetRevision: main
    path: apps/test-client/overlays/cluster-b

  destination:
    name: 002-cluster
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true